[package]
name = "polyspec-ssr-build"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
polyspec-ssr-core = { path = "../polyspec-ssr-core", version = "=0.0.1" }
ordered-json.workspace = true
rolldown.workspace = true
rolldown_common.workspace = true
rolldown_plugin_utils.workspace = true
rolldown_sourcemap.workspace = true
lightningcss.workspace = true
sha2.workspace = true
getrandom.workspace = true
sourcemap.workspace = true
deno_core.workspace = true
tokio.workspace = true
