[graph]
all-features = true

[advisories]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Unicode-3.0", "Zlib", "MPL-2.0"]

[[licenses.exceptions]]
name = "xxhash-rust"
version = "=0.8.18"
allow = ["BSL-1.0"]

[[licenses.exceptions]]
name = "dragonbox_ecma"
version = "=0.1.12"
allow = ["Apache-2.0 WITH LLVM-exception"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
