[package]
name = "ssr-server"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
http.workspace = true
ssr-build = { path = "../ssr-build", version = "=0.0.1" }
ssr-core = { path = "../ssr-core", version = "=0.0.1" }
ssr-runtime = { path = "../ssr-runtime", version = "=0.0.1" }
ssr-adapter-react = { path = "../ssr-adapter-react", version = "=0.0.1" }
ssr-adapter-svelte = { path = "../ssr-adapter-svelte", version = "=0.0.1" }
ssr-adapter-vanilla = { path = "../ssr-adapter-vanilla", version = "=0.0.1" }
sourcemap.workspace = true
tracing.workspace = true
sha2.workspace = true
notify.workspace = true
tokio.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
lol_html.workspace = true
getrandom.workspace = true

[dev-dependencies]
sha2.workspace = true
tracing-subscriber = { version = "=0.3.23", default-features = false, features = ["fmt"] }
tokio.workspace = true
hyper = { workspace = true, features = ["server"] }

[[example]]
name = "development_process"
path = "tests/support/development_process.rs"
